name: CI

on: # quando eu tiver um push
  pull_request: # quando eu tiver um pull request
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest # test roda nessa máquina virtual
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # checkout do código

      - name: Instala o node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instala as dependências
        run: npm install

      - name: Roda os testes
        run: npm test
